# Generated by Django 5.1 on 2024-09-01 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estampa', '0001_initial'),
        ('pedido', '0003_itempedido_estampa_itempedido_tamanho'),
        ('produto', '0009_alter_produto_estampas_alter_produto_tamanho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='estampa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estampa.estampa'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='tamanho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.tamanho'),
        ),
    ]
