# Generated by Django 5.0.6 on 2024-08-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_cpf_alter_usuario_tipo_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_cliente',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('CORPORATIVO', 'Corporativo'), ('ADMINISTRADOR', 'Administrador')], default='CLIENTE', max_length=20),
        ),
    ]
