# Generated by Django 5.0.6 on 2024-08-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estampa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('CAMISA', 'Camisa'), ('CAMISETA', 'Camiseta'), ('OUTRO', 'Outro')], default='CAMISETA', max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tamanho', models.CharField(max_length=5)),
                ('quantidade_em_estoque', models.IntegerField(default=0)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('estampas', models.ManyToManyField(blank=True, related_name='produtos', to='estampa.estampa')),
            ],
        ),
    ]
