# Generated by Django 5.0.6 on 2024-08-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('CAMISA', 'Camisa'), ('CAMISETA', 'Camiseta'), ('CALCA', 'Calça'), ('SAIA', 'Saia'), ('JAQUETA', 'Jaqueta'), ('ACESSORIO', 'Acessório'), ('VESTIDO', 'Vestido'), ('OUTRO', 'Outro')], default='CAMISETA', max_length=20),
        ),
    ]
