# Generated by Django 5.0.6 on 2024-08-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('CAMISA', 'Camisa'), ('CAMISETA', 'Camiseta'), ('JAQUETA', 'Jaqueta'), ('ACESSORIO', 'Acessório'), ('VESTIDO', 'Vestido'), ('OUTRO', 'Outro')], default='CAMISETA', max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='tipo',
        ),
        migrations.AddField(
            model_name='produto',
            name='tipos',
            field=models.ManyToManyField(related_name='produtos', to='produto.tipoproduto'),
        ),
    ]
