# Generated by Django 5.0.6 on 2024-08-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_tipoproduto_remove_produto_tipo_produto_tipos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproduto',
            name='nome',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
