# Generated by Django 5.1 on 2024-08-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estampa', '0001_initial'),
        ('produto', '0007_rename_tipoproduto_categoriaproduto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estampas',
            field=models.ManyToManyField(blank=True, null=True, related_name='produtos', to='estampa.estampa'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tamanho',
            field=models.ManyToManyField(blank=True, null=True, related_name='produto', to='produto.tamanho'),
        ),
    ]
