# Generated by Django 5.1 on 2024-09-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estampa', '0001_initial'),
        ('produto', '0008_alter_produto_estampas_alter_produto_tamanho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estampas',
            field=models.ManyToManyField(blank=True, related_name='produtos', to='estampa.estampa'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tamanho',
            field=models.ManyToManyField(blank=True, related_name='produto', to='produto.tamanho'),
        ),
    ]
