# Generated by Django 5.1 on 2024-09-01 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0002_itemcarrinho_estampa_itemcarrinho_tamanho'),
        ('estampa', '0001_initial'),
        ('produto', '0008_alter_produto_estampas_alter_produto_tamanho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrinho',
            name='estampa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estampa.estampa'),
        ),
        migrations.AlterField(
            model_name='itemcarrinho',
            name='tamanho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.tamanho'),
        ),
    ]
